[2024-04-16T09:05:13.940+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T08:00:00+00:00 map_index=5 [queued]>
[2024-04-16T09:05:13.965+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T08:00:00+00:00 map_index=5 [queued]>
[2024-04-16T09:05:13.966+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-16T09:05:14.049+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-16 08:00:00+00:00
[2024-04-16T09:05:14.078+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-16T08:00:00+00:00', '--job-id', '3931', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp9j76cdtf', '--map-index', '5']
[2024-04-16T09:05:14.081+0000] {standard_task_runner.py:88} INFO - Job 3931: Subtask ETL_job
[2024-04-16T09:05:14.057+0000] {standard_task_runner.py:60} INFO - Started process 328727 to run task
[2024-04-16T09:05:14.209+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-16T08:00:00+00:00 map_index=5 [running]> on host a09da322e808
[2024-04-16T09:05:14.470+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T08:00:00+00:00'
[2024-04-16T09:05:14.472+0000] {Units_dag.py:90} INFO - i: 50000, chunk: 10000
[2024-04-16T09:05:14.472+0000] {Units_dag.py:91} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzEzMjU4MDAzLCJleHAiOjE3MTU4NTAwMDMsIm5iZiI6MTcxMzI1ODAwMywianRpIjoiakp0VGh2dDA5dm43aTg1MCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.EmbZ0RY9u-BHgdA5VeLM7OzJeWMA1HPlvUHXPTnVNQI
[2024-04-16T09:05:36.732+0000] {Units_dag.py:95} INFO - {'_id': '62ab458332c7ff1e00587887', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '3634 - R R A', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '357073291539225', 'sim_number': '+966830028529377', 'sim_serial': '996609821110934444', 'device_serial': '1118913881', 'device': 'teltonika', 'user_id': '629360b2304a1a239b77a766', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2023-12-31 11:30:22', 'created_at': '2022-06-16 18:00:19', 'creator': 'amr.ahmed', 'company': '', 'owner': 'kwality-ice-cream-admin', 'last_update': {'dtt': 1709007600000, 'dts': 1709007705140, 'spd': 0, 'ang': 111, 'alt': 14, 'chPrams': {'Speed': {'v': 0, 'cdt': 1707552624000}, 'output1': {'v': False, 'cdt': 1709006699000}, 'output2': {'v': False, 'cdt': 1709006699000}, 'parm24': {'v': 0, 'cdt': 1707552624000}, 'ePwrV': {'v': 8.692, 'cdt': 1709007600000}, 'sat': {'v': 12, 'cdt': 1709007600000}, 'ai1': {'v': 1615, 'cdt': 1709007600000}, 'priority': {'v': 0, 'cdt': 1707228438000}, 'type': {'v': 6, 'cdt': 1708473239000}, 'di2': {'v': 0, 'cdt': 1708593456000}, 'di1': {'v': 0, 'cdt': 1707552624000}, 'result': {'v': '5665723a30332e32372e30375f3030204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353730373332393135333932323520496e69743a323032342d322d3820393a353820557074696d653a31363138343838204d41433a303031453432373333313145205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1709007600000}, 'protocol': {'v': 'teltonika', 'cdt': 1709007300000}, 'parm6': {'v': 86, 'cdt': 1708606078000}, 'temp5': {'v': 30, 'cdt': 1666171917000}, 'parm29': {'v': 0, 'cdt': 1708435371000}, 'iPwrV': {'v': 3.587, 'cdt': 1709007600000}, 'humidity86': {'v': 300, 'cdt': 1663865198000}, 'event': {'v': 0, 'cdt': 1707226934000}}, 'prms': {'protocol': 'teltonika', 'priority': 0, 'sat': 12, 'event': 0, 'di1': 0, 'output1': 0, 'di2': 0, 'output2': 0, 'parm29': 0, 'ePwrV': 8.692, 'Speed': 0, 'parm24': 0, 'iPwrV': 3.587, 'ai1': 1615, 'parm6': 86, 'type': 6, 'result': '5665723a30332e32372e30375f3030204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353730373332393135333932323520496e69743a323032342d322d3820393a353820557074696d653a31363138343838204d41433a303031453432373333313145205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34'}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'di2', 'output2', 'parm29', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1', 'parm6', 'type', 'result'], 'old_params': {'protocol': 'teltonika', 'priority': 0, 'sat': 12, 'event': 0, 'di1': 0, 'output1': 0, 'di2': 0, 'output2': 0, 'parm29': 0, 'ePwrV': 8.692, 'Speed': 0, 'parm24': 0, 'iPwrV': 3.587, 'ai1': 1615, 'parm6': 86}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.243.162', 'rl': 0, 'trl': 56254.9963, 'mdu': 0, 'tmdu': 5725891, 'eidl': 0, 'teidl': 2155034, 'fc': 0, 'tfc': 1.04418, 'acc': 0, 'accOn': 27971295, 'accOff': 2427755483, 'sdu': 0, 'tsdu': 1454976, 'lat': 21.3636016, 'lng': 39.2003416}, 'counters': {'odometer_type': 'gps', 'odometer': 56255, 'engine_hours_type': 'acc', 'engine_hours': 27971295, 'last_acc': 0}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-16T09:05:37.216+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:05:37.283+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:05:37.330+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:05:37.365+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T09:05:37.492+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.159s]
[2024-04-16T09:05:37.935+0000] {_transport.py:358} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:N/A duration:0.002s]
[2024-04-16T09:05:37.935+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-04-16T09:05:37.935+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7faa177d43a0>: Failed to establish a new connection: [Errno 111] Connection refused)
[2024-04-16T09:05:37.937+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T09:05:37.951+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.014s]
[2024-04-16T09:05:37.951+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-04-16T09:05:37.951+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 1 of 3)
[2024-04-16T09:05:37.974+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T09:05:38.226+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.274s]
[2024-04-16T09:05:38.337+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-04-16T09:05:38.368+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=5, execution_date=20240416T080000, start_date=20240416T090513, end_date=20240416T090538
[2024-04-16T09:05:38.398+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3931 for task ETL_job (10000 document(s) failed to index.; 328727)
[2024-04-16T09:05:38.451+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-16T09:05:38.477+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
