[2024-05-06T09:40:21.168+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T09:20:00+00:00 map_index=7 [queued]>
[2024-05-06T09:40:21.228+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T09:20:00+00:00 map_index=7 [queued]>
[2024-05-06T09:40:21.229+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-06T09:40:21.363+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-06 09:20:00+00:00
[2024-05-06T09:40:21.387+0000] {standard_task_runner.py:60} INFO - Started process 804706 to run task
[2024-05-06T09:40:21.441+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-06T09:20:00+00:00', '--job-id', '35304', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp0l4fpt2r', '--map-index', '7']
[2024-05-06T09:40:21.492+0000] {standard_task_runner.py:88} INFO - Job 35304: Subtask ETL_job
[2024-05-06T09:40:21.773+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T09:20:00+00:00 map_index=7 [running]> on host a09da322e808
[2024-05-06T09:40:22.330+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T09:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T09:20:00+00:00'
[2024-05-06T09:40:22.332+0000] {Units_dag.py:99} INFO - i: 70000, chunk: 10000
[2024-05-06T09:40:22.332+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE0OTg4NDA0LCJleHAiOjE3MTc1ODA0MDQsIm5iZiI6MTcxNDk4ODQwNCwianRpIjoiYUJSYUxtNWptZ00zYmFKRyIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.kp1UYjfJozM18B2ZprMMqCTdLTIUB_4-u3NvpeTPujE
[2024-05-06T09:40:52.285+0000] {Units_dag.py:104} INFO - {'_id': '63a302c14478524b417eaff9', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': None, 'measurement_type': 'count', 'max_capacity': 0, 'vin': None, 'plate_number': '2695 ESA', 'start_operation': None, 'contract_milage': None, 'opening_milage': None, 'model': None, 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '5100076', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '350424060146394', 'sim_number': '+966830028777648', 'sim_serial': '996609821111018530', 'device_serial': '1125683442', 'device': 'teltonika', 'user_id': '633ed22ee267ca0078423ef3', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-22 12:08:10', 'created_at': '2022-12-21 15:57:37', 'skip_sim_information': '', 'custom_fields': [], 'shipment_info': None, 'creator': 'amr.ahmed', 'company': '', 'owner': 'herfy-food-admin', 'last_update': {'dtt': 1714988390000, 'dts': 1714988393464, 'spd': 0, 'ang': 60, 'alt': 16, 'chPrams': {'Speed': {'v': 0, 'cdt': 1714988390000}, 'output1': {'v': False, 'cdt': 1714935870000}, 'output2': {'v': False, 'cdt': 1714935870000}, 'ePwrV': {'v': 28.404, 'cdt': 1714988390000}, 'parm24': {'v': 0, 'cdt': 1714988390000}, 'sat': {'v': 19, 'cdt': 1714988384000}, 'ai1': {'v': 11623, 'cdt': 1714988390000}, 'type': {'v': 6, 'cdt': 1712920955000}, 'di2': {'v': 0, 'cdt': 1713242973000}, 'priority': {'v': 0, 'cdt': 1714719252000}, 'di1': {'v': 1, 'cdt': 1714987439000}, 'result': {'v': '5665723a30332e32372e31335f3033204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353034323430363031343633393420496e69743a323032342d352d3320363a343920557074696d653a323635353234204d41433a333838413231303246394446205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1714984931000}, 'protocol': {'v': 'FMB120', 'cdt': 1714984958000}, 'parm6': {'v': 130, 'cdt': 1714980015000}, 'parm29': {'v': 0, 'cdt': 1714784560000}, 'iPwrV': {'v': 4.082, 'cdt': 1714988390000}, 'event': {'v': 0, 'cdt': 1714719252000}}, 'prms': {'protocol': 'FMB120', 'priority': 0, 'sat': 19, 'event': 0, 'di1': 1, 'output1': 0, 'di2': 0, 'output2': 0, 'parm29': 0, 'ePwrV': 28.404, 'Speed': 0, 'parm24': 0, 'iPwrV': 4.082, 'ai1': 11623, 'parm6': 130}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'di2', 'output2', 'parm29', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1', 'parm6', 'type', 'result'], 'old_params': {'protocol': 'FMB120', 'priority': 0, 'sat': 19, 'event': 0, 'di1': 1, 'output1': 0, 'di2': 0, 'output2': 0, 'parm29': 0, 'ePwrV': 28.319, 'Speed': 16, 'parm24': 16, 'iPwrV': 4.0760000000000005, 'ai1': 11267, 'parm6': 130}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.238.75', 'rl': 0.0113, 'trl': 37735.3623, 'mdu': 6, 'tmdu': 2972217, 'eidl': 0, 'teidl': 4099456, 'fc': 0.001356, 'tfc': 367.79784, 'acc': 1, 'accOn': 8299410, 'accOff': 35856450, 'sdu': 0, 'tsdu': 0, 'lat': 26.3970483, 'lng': 50.0427066}, 'counters': {'odometer_type': 'gps', 'odometer': 37735.1856, 'engine_hours_type': 'acc', 'engine_hours': 8299410, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-06T09:40:54.631+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T09:40:54.726+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T09:40:54.803+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T09:40:54.829+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T09:40:54.895+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.090s]
[2024-05-06T09:40:55.737+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T09:40:55.764+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.052s]
[2024-05-06T09:40:55.765+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-06T09:40:55.765+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-06T09:40:55.766+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T09:40:55.943+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.177s]
[2024-05-06T09:40:56.341+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-06T09:40:56.355+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=7, execution_date=20240506T092000, start_date=20240506T094021, end_date=20240506T094056
[2024-05-06T09:40:56.371+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35304 for task ETL_job (10000 document(s) failed to index.; 804706)
[2024-05-06T09:40:56.447+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T09:40:56.491+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
