[2024-04-29T14:04:42.490+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T13:40:00+00:00 map_index=9 [queued]>
[2024-04-29T14:04:42.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T13:40:00+00:00 map_index=9 [queued]>
[2024-04-29T14:04:42.508+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-29T14:04:42.531+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-29 13:40:00+00:00
[2024-04-29T14:04:42.538+0000] {standard_task_runner.py:60} INFO - Started process 639936 to run task
[2024-04-29T14:04:42.546+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-29T13:40:00+00:00', '--job-id', '23126', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp1q4qtvl2', '--map-index', '9']
[2024-04-29T14:04:42.549+0000] {standard_task_runner.py:88} INFO - Job 23126: Subtask ETL_job
[2024-04-29T14:04:42.657+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-29T13:40:00+00:00 map_index=9 [running]> on host a09da322e808
[2024-04-29T14:04:42.838+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T13:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T13:40:00+00:00'
[2024-04-29T14:04:42.840+0000] {Units_dag.py:99} INFO - i: 90000, chunk: 10000
[2024-04-29T14:04:42.840+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE0Mzk5MjA0LCJleHAiOjE3MTY5OTEyMDQsIm5iZiI6MTcxNDM5OTIwNCwianRpIjoiV2JUNnU0UUZWWk50Z3Q5TiIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.tVP0N8r6XYfHHbyxyguTZtK0S7EUhhtlsm4GjqIITis
[2024-04-29T14:05:02.161+0000] {Units_dag.py:104} INFO - {'_id': '640d88a6fd83f47c487ff3d7', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': 'أ ر ى 9810', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'DT71009-9810VRA', 'operation_code': '9810VRA', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '869688059175473', 'sim_number': '+966830031778776', 'sim_serial': '21296774031', 'device_serial': '869688059175473', 'device': 'bce', 'user_id': '5f8bf21303ed52b7fb1c11ba', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-03-12 11:09:10', 'skip_sim_information': '', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'alwefaq-rent', 'last_update': {'dtt': 1714398718000, 'dts': 1714398746208, 'spd': 0, 'ang': 284, 'alt': 1698, 'chPrams': {'ePwrV': {'v': 28.254, 'cdt': 1714398718000}, 'di16': {'v': 1, 'cdt': 1712305878000}, 'di15': {'v': 0, 'cdt': 1678609020000}, 'rssi1': {'v': 62, 'cdt': 1714398718000}, 'di14': {'v': 0, 'cdt': 1714398718000}, 'di13': {'v': 0, 'cdt': 1712858694000}, 'di12': {'v': 0, 'cdt': 1712305878000}, 'di11': {'v': 0, 'cdt': 1712305878000}, 'di10': {'v': 0, 'cdt': 1712305878000}, 'di2': {'v': 0, 'cdt': 1711892378000}, 'di1': {'v': 1, 'cdt': 1714398528000}, 'ai4': {'v': 382, 'cdt': 1714398718000}, 'di4': {'v': 0, 'cdt': 1712305878000}, 'di3': {'v': 0, 'cdt': 1712305878000}, 'di6': {'v': 0, 'cdt': 1712305878000}, 'di5': {'v': 0, 'cdt': 1712604184000}, 'lac1': {'v': 42007, 'cdt': 1714297900000}, 'protocol': {'v': 'bce', 'cdt': 1712305878000}, 'di8': {'v': 1, 'cdt': 1712305878000}, 'di7': {'v': 1, 'cdt': 1714395924000}, 'di9': {'v': 0, 'cdt': 1712305878000}, 'iPwrV': {'v': 4.069, 'cdt': 1714398718000}, 'humidity': {'v': -1, 'cdt': 1712305878000}, 'ID': {'v': '0', 'cdt': 1712858694000}, 'cid1': {'v': 11471, 'cdt': 1714398718000}, 'temp': {'v': -273, 'cdt': 1712940290000}, 'odometer': {'v': 1117962838, 'cdt': 1714398718000}, 'spd': {'v': 0, 'cdt': 1714398718000}, 'sat': {'v': 12, 'cdt': 1714398612000}, 'hdop': {'v': 1, 'cdt': 1714384498000}, 'ta': {'v': 0, 'cdt': 1712305878000}, 'mcc1': {'v': 420, 'cdt': 1714290608000}, 'mnc1': {'v': 4, 'cdt': 1712497698000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 1117962838, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 1, 'ePwrV': 28.254, 'ai4': 382, 'iPwrV': 4.069, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 42007, 'cid1': 11471, 'rssi1': 62, 'ID': '0', 'temp': -273, 'humidity': -1}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1', 'ID', 'temp', 'humidity'], 'old_params': {'protocol': 'bce', 'spd': 12, 'sat': 12, 'hdop': 1, 'odometer': 1090653473, 'di16': 1, 'di15': 0, 'di14': 1, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 1, 'ePwrV': 28.342, 'ai4': 340, 'iPwrV': 4.072, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 42007, 'cid1': 12721, 'rssi1': 69, 'ID': '0', 'temp': -273, 'humidity': -1}, 'vLoc': 1, 'vCon': 1, 'ip': '51.39.236.170', 'rl': 0, 'trl': 699.5551, 'mdu': 0, 'tmdu': 38718, 'eidl': 0, 'teidl': 2646218, 'fc': 0, 'tfc': 0, 'acc': 0, 'accOn': 2870030, 'accOff': 32504946, 'sdu': 0, 'tsdu': 0, 'lat': 21.25172996520996, 'lng': 40.41370391845703}, 'counters': {'odometer_type': 'gps', 'odometer': 699.553, 'engine_hours_type': 'acc', 'engine_hours': 2870030, 'last_acc': 0}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-29T14:05:02.897+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T14:05:02.956+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T14:05:03.017+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-29T14:05:03.158+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-29T14:05:03.236+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.217s]
[2024-04-29T14:05:03.760+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-29T14:05:05.726+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:1.984s]
[2024-04-29T14:05:06.070+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 3326 document(s) failed to index.
[2024-04-29T14:05:06.083+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=9, execution_date=20240429T134000, start_date=20240429T140442, end_date=20240429T140506
[2024-04-29T14:05:06.102+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23126 for task ETL_job (3326 document(s) failed to index.; 639936)
[2024-04-29T14:05:06.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-29T14:05:06.213+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
