[2024-05-12T08:00:15.857+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=3 [queued]>
[2024-05-12T08:00:15.912+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=3 [queued]>
[2024-05-12T08:00:15.912+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-12T08:00:15.990+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-12 07:40:00+00:00
[2024-05-12T08:00:16.001+0000] {standard_task_runner.py:60} INFO - Started process 962867 to run task
[2024-05-12T08:00:16.042+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-12T07:40:00+00:00', '--job-id', '53505', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmppk8oa7uj', '--map-index', '3']
[2024-05-12T08:00:16.066+0000] {standard_task_runner.py:88} INFO - Job 53505: Subtask ETL_job
[2024-05-12T08:00:16.507+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-12T07:40:00+00:00 map_index=3 [running]> on host a09da322e808
[2024-05-12T08:00:17.202+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T07:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T07:40:00+00:00'
[2024-05-12T08:00:17.204+0000] {Units_dag.py:98} INFO - i: 30000, chunk: 10000
[2024-05-12T08:00:17.204+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1NTAwODA0LCJleHAiOjE3MTgwOTI4MDQsIm5iZiI6MTcxNTUwMDgwNCwianRpIjoidlR6a1FSaEpwakgwRG02ciIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.vq3d2BTkxMJIh5ziQneZBO3fVC3uiD8DjKINBVKE9qo
[2024-05-12T08:00:49.626+0000] {Units_dag.py:103} INFO - {'_id': '621751ac6f6cd70bf837adde', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'weight', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'العالمية - SNG-7 2023-06-05', 'operation_code': '2307 - ZDB', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '866854051782293', 'sim_number': '+966830020160139', 'sim_serial': '8996641520415664657', 'device_serial': '866854051782293', 'device': 'bce', 'user_id': '619b47e8a0de2d54c7741f56', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-02-24 12:36:44', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'general-commission-admin', 'last_update': {'dtt': 1715466314000, 'dts': 1715466381231, 'spd': 0, 'ang': 204, 'alt': 622, 'chPrams': {'ePwrV': {'v': 0.4, 'cdt': 1715464516000}, 'di16': {'v': 1, 'cdt': 1715355840000}, 'rssi1': {'v': 43, 'cdt': 1715465716000}, 'di15': {'v': 0, 'cdt': 1715355840000}, 'di14': {'v': 0, 'cdt': 1714766798000}, 'di13': {'v': 0, 'cdt': 1715355840000}, 'di12': {'v': 0, 'cdt': 1715355840000}, 'di11': {'v': 0, 'cdt': 1715355840000}, 'di10': {'v': 0, 'cdt': 1715355840000}, 'di2': {'v': 1, 'cdt': 1714162252000}, 'di1': {'v': 0, 'cdt': 1715176078000}, 'di4': {'v': 0, 'cdt': 1715355840000}, 'di3': {'v': 0, 'cdt': 1715355840000}, 'di6': {'v': 1, 'cdt': 1715355840000}, 'di5': {'v': 0, 'cdt': 1715464216000}, 'lac1': {'v': 1231, 'cdt': 1715119942000}, 'protocol': {'v': 'bce', 'cdt': 1715355840000}, 'di8': {'v': 1, 'cdt': 1715355840000}, 'di7': {'v': 0, 'cdt': 1715176078000}, 'di9': {'v': 0, 'cdt': 1715355840000}, 'iPwrV': {'v': 3.673, 'cdt': 1715466314000}, 'cid1': {'v': 14453, 'cdt': 1715464180000}, 'odometer': {'v': 0, 'cdt': 1715121020000}, 'spd': {'v': 0, 'cdt': 1715121020000}, 'sat': {'v': 15, 'cdt': 1715460580000}, 'hdop': {'v': 1, 'cdt': 1715114178000}, 'ta': {'v': 0, 'cdt': 1715355840000}, 'mcc1': {'v': 420, 'cdt': 1715355840000}, 'mnc1': {'v': 3, 'cdt': 1715355840000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 15, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 1, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 0.4, 'iPwrV': 3.673, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 1231, 'cid1': 14453, 'rssi1': 43}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'di16': 1, 'ePwrV': 0.4, 'di15': 0, 'rssi1': 43, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di2': 1, 'di1': 0, 'di4': 0, 'di3': 0, 'di6': 1, 'di5': 0, 'lac1': 1231, 'protocol': 'bce', 'di8': 1, 'di7': 0, 'di9': 0, 'iPwrV': 3.697, 'cid1': 14453, 'odometer': 0, 'spd': 0, 'sat': 15, 'hdop': 1, 'ta': 0, 'mcc1': 420, 'mnc1': 3}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.22.117', 'rl': 0, 'trl': 3487.123, 'mdu': 0, 'tmdu': 184954, 'eidl': 0, 'teidl': 353588, 'fc': 0, 'tfc': 0.00282, 'acc': 0, 'accOn': 84622858, 'accOff': 27132140, 'sdu': 298, 'tsdu': 2098, 'lat': 24.6634578704834, 'lng': 46.73871994018555}, 'counters': {'odometer_type': 'gps', 'odometer': 3487.1185, 'engine_hours_type': 'acc', 'engine_hours': 84622858, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-12T08:00:50.384+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:00:50.479+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:00:50.561+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-12T08:00:50.594+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:00:50.705+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.142s]
[2024-05-12T08:00:51.206+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:00:51.220+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.036s]
[2024-05-12T08:00:51.221+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-12T08:00:51.221+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-12T08:00:51.222+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:00:51.235+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.014s]
[2024-05-12T08:00:51.236+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-12T08:00:51.236+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 1 of 3)
[2024-05-12T08:00:51.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-12T08:00:51.426+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.189s]
[2024-05-12T08:00:51.793+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-12T08:00:51.807+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=3, execution_date=20240512T074000, start_date=20240512T080015, end_date=20240512T080051
[2024-05-12T08:00:51.825+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53505 for task ETL_job (10000 document(s) failed to index.; 962867)
[2024-05-12T08:00:51.901+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-12T08:00:51.939+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
