[2024-04-18T00:12:04.133+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T22:17:48.106544+00:00 map_index=11 [queued]>
[2024-04-18T00:12:04.198+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T22:17:48.106544+00:00 map_index=11 [queued]>
[2024-04-18T00:12:04.198+0000] {taskinstance.py:2193} INFO - Starting attempt 10 of 11
[2024-04-18T00:12:04.328+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-14 22:17:48.106544+00:00
[2024-04-18T00:12:04.359+0000] {standard_task_runner.py:60} INFO - Started process 367847 to run task
[2024-04-18T00:12:04.396+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'manual__2024-04-14T22:17:48.106544+00:00', '--job-id', '6551', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmplkj2hyyf', '--map-index', '11']
[2024-04-18T00:12:04.398+0000] {standard_task_runner.py:88} INFO - Job 6551: Subtask ETL_job
[2024-04-18T00:12:04.671+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T22:17:48.106544+00:00 map_index=11 [running]> on host a09da322e808
[2024-04-18T00:12:05.227+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T22:17:48.106544+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T22:17:48.106544+00:00'
[2024-04-18T00:12:05.242+0000] {Units_dag.py:99} INFO - i: 110000, chunk: 10000
[2024-04-18T00:12:05.242+0000] {Units_dag.py:100} INFO - child token is::: None
[2024-04-18T00:12:05.242+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    units_list = Utils.get_all_units_api(args[0], args[1],child_token)
  File "/opt/airflow/dags/utilities.py", line 15, in get_all_units_api
    response = _ApiCaller.post(Globals.api_endpoint+"units/lists?token="+child_token, data_payload)
TypeError: can only concatenate str (not "NoneType") to str
[2024-04-18T00:12:05.278+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=11, execution_date=20240414T221748, start_date=20240418T001204, end_date=20240418T001205
[2024-04-18T00:12:05.493+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6551 for task ETL_job (can only concatenate str (not "NoneType") to str; 367847)
[2024-04-18T00:12:05.589+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-18T00:12:05.646+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
