[2024-05-13T19:32:15.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T19:32:16.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AVL_DAG.concat_groups_connection_string manual__2024-05-13T19:31:53.465140+00:00 [queued]>
[2024-05-13T19:32:16.039+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AVL_DAG.concat_groups_connection_string manual__2024-05-13T19:31:53.465140+00:00 [queued]>
[2024-05-13T19:32:16.039+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-13T19:32:16.063+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): concat_groups_connection_string> on 2024-05-13 19:31:53.465140+00:00
[2024-05-13T19:32:16.072+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1931) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T19:32:16.075+0000] {standard_task_runner.py:63} INFO - Started process 1932 to run task
[2024-05-13T19:32:16.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AVL_DAG', 'concat_groups_connection_string', 'manual__2024-05-13T19:31:53.465140+00:00', '--job-id', '56512', '--raw', '--subdir', 'DAGS_FOLDER/Avl_dag.py', '--cfg-path', '/tmp/tmp1szy10gh']
[2024-05-13T19:32:16.084+0000] {standard_task_runner.py:91} INFO - Job 56512: Subtask concat_groups_connection_string
[2024-05-13T19:32:16.168+0000] {task_command.py:426} INFO - Running <TaskInstance: AVL_DAG.concat_groups_connection_string manual__2024-05-13T19:31:53.465140+00:00 [running]> on host 117fd00757b6
[2024-05-13T19:32:16.334+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='AVL_DAG' AIRFLOW_CTX_TASK_ID='concat_groups_connection_string' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T19:31:53.465140+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T19:31:53.465140+00:00'
[2024-05-13T19:32:16.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T19:32:16.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T19:32:16.337+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/avl_pipeline/utilities.py", line 18, in concat_groups_connection_string
    units_group_by_signal_conn_id =  kwargs['ti'].xcom_push(key='units_group_by_signal_conn_id')
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_push() missing 1 required positional argument: 'value'
[2024-05-13T19:32:16.352+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=AVL_DAG, task_id=concat_groups_connection_string, run_id=manual__2024-05-13T19:31:53.465140+00:00, execution_date=20240513T193153, start_date=20240513T193216, end_date=20240513T193216
[2024-05-13T19:32:16.370+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56512 for task concat_groups_connection_string (TaskInstance.xcom_push() missing 1 required positional argument: 'value'; 1932)
[2024-05-13T19:32:16.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T19:32:16.450+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T19:32:16.455+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
