[2024-04-18T00:12:55.056+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T23:47:14.516395+00:00 map_index=3 [queued]>
[2024-04-18T00:12:55.112+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T23:47:14.516395+00:00 map_index=3 [queued]>
[2024-04-18T00:12:55.112+0000] {taskinstance.py:2193} INFO - Starting attempt 8 of 9
[2024-04-18T00:12:55.291+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-14 23:47:14.516395+00:00
[2024-04-18T00:12:55.310+0000] {standard_task_runner.py:60} INFO - Started process 368090 to run task
[2024-04-18T00:12:55.385+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'manual__2024-04-14T23:47:14.516395+00:00', '--job-id', '6658', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp60z35v69', '--map-index', '3']
[2024-04-18T00:12:55.395+0000] {standard_task_runner.py:88} INFO - Job 6658: Subtask ETL_job
[2024-04-18T00:12:55.704+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-14T23:47:14.516395+00:00 map_index=3 [running]> on host a09da322e808
[2024-04-18T00:12:56.429+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T23:47:14.516395+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T23:47:14.516395+00:00'
[2024-04-18T00:12:56.430+0000] {Units_dag.py:99} INFO - i: 30000, chunk: 10000
[2024-04-18T00:12:56.431+0000] {Units_dag.py:100} INFO - child token is::: None
[2024-04-18T00:12:56.431+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    units_list = Utils.get_all_units_api(args[0], args[1],child_token)
  File "/opt/airflow/dags/utilities.py", line 15, in get_all_units_api
    response = _ApiCaller.post(Globals.api_endpoint+"units/lists?token="+child_token, data_payload)
TypeError: can only concatenate str (not "NoneType") to str
[2024-04-18T00:12:56.506+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=3, execution_date=20240414T234714, start_date=20240418T001255, end_date=20240418T001256
[2024-04-18T00:12:56.563+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6658 for task ETL_job (can only concatenate str (not "NoneType") to str; 368090)
[2024-04-18T00:12:56.656+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-18T00:12:56.692+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
