[2024-05-10T18:00:16.252+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T17:40:00+00:00 map_index=15 [queued]>
[2024-05-10T18:00:16.302+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T17:40:00+00:00 map_index=15 [queued]>
[2024-05-10T18:00:16.303+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-10T18:00:16.390+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-10 17:40:00+00:00
[2024-05-10T18:00:16.448+0000] {standard_task_runner.py:60} INFO - Started process 920013 to run task
[2024-05-10T18:00:16.519+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-10T17:40:00+00:00', '--job-id', '48334', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmps133yyrx', '--map-index', '15']
[2024-05-10T18:00:16.561+0000] {standard_task_runner.py:88} INFO - Job 48334: Subtask ETL_job
[2024-05-10T18:00:17.093+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T17:40:00+00:00 map_index=15 [running]> on host a09da322e808
[2024-05-10T18:00:17.679+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T17:40:00+00:00'
[2024-05-10T18:00:17.680+0000] {Units_dag.py:98} INFO - i: 150000, chunk: 10000
[2024-05-10T18:00:17.681+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MzY0MDA1LCJleHAiOjE3MTc5NTYwMDUsIm5iZiI6MTcxNTM2NDAwNSwianRpIjoieGFsVFJuOTdGNWxTUk9pTCIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.2h8Ud1DI4JIP68BACNkFbCF9-ovqKuwqoPI2bjNNO5E
[2024-05-10T18:00:41.550+0000] {Units_dag.py:103} INFO - {'_id': '659bf82743ca0211150f8273', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'name': '5922BER', 'operation_code': '', 'device_gateway': '', 'skip_sim_information': False, 'imei': '866069060821301', 'sim_number': '+966830020337741', 'sim_serial': '8996609821112128732', 'device_serial': '1135686265', 'device': 'teltonika', 'user_id': '631866bf3cdfd0479c43062d', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2024-01-08 16:27:03', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'dar-almerkaba-admin', 'last_update': {'dtt': 1715362767000, 'dts': 1715362770904, 'spd': 0, 'ang': 0, 'alt': 0, 'chPrams': {'Speed': {'v': 0, 'cdt': 1715352356000}, 'output1': {'v': False, 'cdt': 1715362166000}, 'ePwrV': {'v': 12.939, 'cdt': 1715362767000}, 'parm24': {'v': 0, 'cdt': 1715352356000}, 'sat': {'v': 0, 'cdt': 1715355554000}, 'ai1': {'v': 217, 'cdt': 1713359386000}, 'priority': {'v': 0, 'cdt': 1715164123000}, 'type': {'v': 6, 'cdt': 1715353751000}, 'di1': {'v': 0, 'cdt': 1715352820000}, 'result': {'v': '5665723a30332e32382e30325f313937204750533a41584e5f352e312e392048773a464d43393230204d6f643a3120494d45493a38363630363930363038323133303120496e69743a323032342d352d372031353a313020557074696d653a323637333432204d41433a333838413231393233424334205350433a312830292041584c3a31204f42443a3020424c3a312e31302042543a34', 'cdt': 1715361866000}, 'protocol': {'v': 'FMC920', 'cdt': 1715362166000}, 'iPwrV': {'v': 0, 'cdt': 1704793996000}, 'event': {'v': 0, 'cdt': 1715164425000}}, 'prms': {'protocol': 'FMC920', 'priority': 0, 'sat': 0, 'event': 0, 'di1': 0, 'output1': 0, 'ePwrV': 12.939, 'Speed': 0, 'parm24': 0, 'iPwrV': 0, 'ai1': 217}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1'], 'old_params': {'Speed': 0, 'protocol': 'teltonika', 'output1': 0, 'ePwrV': 12.935, 'parm24': 0, 'sat': 0, 'ai1': 217, 'iPwrV': 0, 'priority': 0, 'event': 0, 'di1': 0}, 'vLoc': 1, 'vCon': 0, 'ip': '37.216.47.43', 'rl': 0, 'trl': 14464.7454, 'mdu': 0, 'tmdu': 1245336, 'eidl': 0, 'teidl': 299133, 'fc': 0, 'tfc': 9.550044, 'acc': 0, 'accOn': 2247328, 'accOff': 9001786, 'sdu': 300, 'tsdu': 9947, 'lat': 24.5664816, 'lng': 46.8517416}, 'counters': {'engine_hours': 2247328, 'last_acc': 0, 'odometer': 14464.613, 'engine_hours_type': '', 'odometer_type': ''}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-10T18:00:43.434+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T18:00:43.644+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T18:00:43.793+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T18:00:43.814+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T18:00:43.891+0000] {_transport.py:335} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:200 duration:0.096s]
[2024-05-10T18:00:44.748+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T18:00:44.765+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.051s]
[2024-05-10T18:00:44.766+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-10T18:00:44.766+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-10T18:00:44.767+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T18:00:44.937+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.171s]
[2024-05-10T18:00:45.762+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-10T18:00:45.789+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=15, execution_date=20240510T174000, start_date=20240510T180016, end_date=20240510T180045
[2024-05-10T18:00:45.819+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 48334 for task ETL_job (10000 document(s) failed to index.; 920013)
[2024-05-10T18:00:45.946+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-10T18:00:45.971+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
