[2024-05-09T13:44:46.844+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T13:20:00+00:00 map_index=15 [queued]>
[2024-05-09T13:44:46.858+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T13:20:00+00:00 map_index=15 [queued]>
[2024-05-09T13:44:46.858+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-05-09T13:44:46.877+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-09 13:20:00+00:00
[2024-05-09T13:44:46.884+0000] {standard_task_runner.py:60} INFO - Started process 888113 to run task
[2024-05-09T13:44:46.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-09T13:20:00+00:00', '--job-id', '44461', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp9dwhbifr', '--map-index', '15']
[2024-05-09T13:44:46.905+0000] {standard_task_runner.py:88} INFO - Job 44461: Subtask ETL_job
[2024-05-09T13:44:47.013+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-09T13:20:00+00:00 map_index=15 [running]> on host a09da322e808
[2024-05-09T13:44:47.180+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T13:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T13:20:00+00:00'
[2024-05-09T13:44:47.182+0000] {Units_dag.py:98} INFO - i: 150000, chunk: 10000
[2024-05-09T13:44:47.182+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MjYyMDA0LCJleHAiOjE3MTc4NTQwMDQsIm5iZiI6MTcxNTI2MjAwNCwianRpIjoibHB6d2JnYU94RVdKckphUSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.r1cjwG-uCks4SSeC4welE_52E44PkcMn7vclmVQrr0s
[2024-05-09T13:45:05.053+0000] {Units_dag.py:103} INFO - {'_id': '659bf8227052ae87300ee1f3', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'measurement_type': 'count', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'shipment_info': {'product_category': '', 'truck_type': '', 'shipment_type': '', 'shipment_payment_type': '', 'transporter_type': '', 'operating_area': '', 'weight_kilograms_per_day': '', 'kms_per_day': '', 'opening_milage': '', 'shipment_trip_drive_hrs_day': '', 'expected_shipment_trip_day': '', 'car_pay_per_day': '', 'exceeding_temperature_limit_per_day': '', 'temperature_upper_limit': '', 'exceeding_humidity_limit_per_day': '', 'humidity_upper_limit': '', 'allowable_delay_drive_hrs_day': ''}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'name': '7855KTR', 'operation_code': None, 'device_gateway': None, 'skip_sim_information': False, 'imei': '866069062284888', 'sim_number': '+966830020785815', 'sim_serial': '8996609821112134924', 'device_serial': '1135867105', 'device': 'teltonika', 'user_id': '61adecadb70c9664dd5bc901', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2024-01-08 16:26:58', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'shift-inc-co', 'last_update': {'dtt': 1715262283000, 'dts': 1715262284873, 'spd': 106, 'ang': 147, 'alt': 624, 'chPrams': {'Speed': {'v': 106, 'cdt': 1715262283000}, 'output1': {'v': False, 'cdt': 1714940718000}, 'ePwrV': {'v': 14.482000000000001, 'cdt': 1715262283000}, 'parm24': {'v': 106, 'cdt': 1715262283000}, 'sat': {'v': 10, 'cdt': 1715262205000}, 'ai1': {'v': 0, 'cdt': 1713952094000}, 'type': {'v': 6, 'cdt': 1713077077000}, 'priority': {'v': 0, 'cdt': 1713951055000}, 'di1': {'v': 1, 'cdt': 1715255555000}, 'result': {'v': '5665723a30332e32382e30325f313937204750533a41584e5f352e312e392048773a464d43393230204d6f643a3120494d45493a38363630363930363232383438383820496e69743a323032342d312d33312031393a353220557074696d653a38343534383335204d41433a333838413231393337443338205350433a312830292041584c3a31204f42443a3020424c3a312e31302042543a34', 'cdt': 1715200586000}, 'protocol': {'v': 'FMC920', 'cdt': 1714940718000}, 'iPwrV': {'v': 4.058, 'cdt': 1715239113000}, 'event': {'v': 0, 'cdt': 1713952094000}}, 'prms': {'protocol': 'FMC920', 'priority': 0, 'sat': 10, 'event': 0, 'di1': 1, 'output1': 0, 'ePwrV': 14.482000000000001, 'Speed': 106, 'parm24': 106, 'iPwrV': 4.058, 'ai1': 0}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1'], 'old_params': {'protocol': 'FMC920', 'priority': 0, 'sat': 10, 'event': 0, 'di1': 1, 'output1': 0, 'ePwrV': 13.48, 'Speed': 108, 'parm24': 108, 'iPwrV': 4.058, 'ai1': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '37.216.53.189', 'rl': 0.7795, 'trl': 66065.3395, 'mdu': 26, 'tmdu': 3902478, 'eidl': 0, 'teidl': 2537022, 'fc': 0.09354, 'tfc': 2086.949856, 'acc': 1, 'accOn': 7591828, 'accOff': 4079158, 'sdu': 0, 'tsdu': 0, 'lat': 24.8881916, 'lng': 46.7179416}, 'counters': {'engine_hours': 7591828, 'last_acc': 1, 'odometer': 66065.2913, 'engine_hours_type': 'acc', 'odometer_type': 'gps'}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-09T13:45:05.592+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T13:45:05.635+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T13:45:05.681+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-09T13:45:05.712+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T13:45:05.768+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.085s]
[2024-05-09T13:45:06.178+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T13:45:06.197+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.040s]
[2024-05-09T13:45:06.197+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-09T13:45:06.197+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-09T13:45:06.198+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-09T13:45:06.350+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.152s]
[2024-05-09T13:45:06.633+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-09T13:45:06.650+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=15, execution_date=20240509T132000, start_date=20240509T134446, end_date=20240509T134506
[2024-05-09T13:45:06.665+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 44461 for task ETL_job (10000 document(s) failed to index.; 888113)
[2024-05-09T13:45:06.710+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-09T13:45:06.743+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
