[2024-04-30T05:20:14.769+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-30T05:00:00+00:00 map_index=14 [queued]>
[2024-04-30T05:20:14.818+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-30T05:00:00+00:00 map_index=14 [queued]>
[2024-04-30T05:20:14.818+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-30T05:20:14.911+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-30 05:00:00+00:00
[2024-04-30T05:20:14.948+0000] {standard_task_runner.py:60} INFO - Started process 655142 to run task
[2024-04-30T05:20:15.002+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-04-30T05:00:00+00:00', '--job-id', '24156', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmphq05osoz', '--map-index', '14']
[2024-04-30T05:20:15.010+0000] {standard_task_runner.py:88} INFO - Job 24156: Subtask ETL_job
[2024-04-30T05:20:15.369+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-04-30T05:00:00+00:00 map_index=14 [running]> on host a09da322e808
[2024-04-30T05:20:16.175+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T05:00:00+00:00'
[2024-04-30T05:20:16.177+0000] {Units_dag.py:99} INFO - i: 140000, chunk: 10000
[2024-04-30T05:20:16.177+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE0NDU0NDAzLCJleHAiOjE3MTcwNDY0MDMsIm5iZiI6MTcxNDQ1NDQwMywianRpIjoiekM3UHRGVE1jOHFrM2tHMSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.c0IFPUnRe5265u_5Xcbp2-2z7lFz8DQirREmoAn9hl4
[2024-04-30T05:20:37.291+0000] {Units_dag.py:104} INFO - {'_id': '654b953dbfed43df3e0bc689', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'name': '2134-AEJ', 'operation_code': '', 'device_gateway': '', 'skip_sim_information': False, 'imei': '350612079289938', 'sim_number': '+966830032299384', 'sim_serial': '8996609821111930990', 'device_serial': '1132787764', 'device': 'teltonika', 'user_id': '62693bbb07a96a0b2714bff8', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-11-08 17:03:41', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'hawadij-rental-admin', 'last_update': {'dtt': 1714454357000, 'dts': 1714454359382, 'spd': 0, 'ang': 59, 'alt': 25, 'chPrams': {'Speed': {'v': 0, 'cdt': 1714418472000}, 'output1': {'v': False, 'cdt': 1714414570000}, 'output2': {'v': False, 'cdt': 1714414570000}, 'ePwrV': {'v': 13.015, 'cdt': 1714454357000}, 'parm24': {'v': 0, 'cdt': 1714418472000}, 'sat': {'v': 16, 'cdt': 1714454357000}, 'ai1': {'v': 218, 'cdt': 1712826437000}, 'priority': {'v': 0, 'cdt': 1712826437000}, 'di2': {'v': 0, 'cdt': 1712826437000}, 'type': {'v': 6, 'cdt': 1712915296000}, 'di1': {'v': 0, 'cdt': 1714418563000}, 'result': {'v': '5665723a30332e32372e31345f3030204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353036313230373932383939333820496e69743a323032342d312d31382032323a313720557074696d653a38373832383430204d41433a333838413231333846413430205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1714414270000}, 'protocol': {'v': 'FMB120', 'cdt': 1714414570000}, 'parm6': {'v': 218, 'cdt': 1713362503000}, 'iPwrV': {'v': 4.071, 'cdt': 1714424003000}, 'event': {'v': 0, 'cdt': 1712826437000}}, 'prms': {'protocol': 'FMB120', 'priority': 0, 'sat': 16, 'event': 0, 'di1': 0, 'output1': 0, 'di2': 0, 'output2': 0, 'ePwrV': 13.015, 'Speed': 0, 'parm24': 0, 'iPwrV': 4.071, 'ai1': 218, 'parm6': 218}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'di2', 'output2', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1', 'parm6'], 'old_params': {'Speed': 0, 'output1': 0, 'output2': 0, 'ePwrV': 13.016, 'parm24': 0, 'sat': 15, 'ai1': 218, 'priority': 0, 'di2': 0, 'di1': 0, 'protocol': 'teltonika', 'parm6': 218, 'iPwrV': 4.071, 'event': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.23.116', 'rl': 0, 'trl': 58754.1349, 'mdu': 0, 'tmdu': 3862247, 'eidl': 0, 'teidl': 1421475, 'fc': 0, 'tfc': 508.3533, 'acc': 0, 'accOn': 5379120, 'accOff': 636151707, 'sdu': 301, 'tsdu': 35794, 'lat': 26.4263849, 'lng': 50.08756}, 'counters': {'engine_hours': 5379120, 'last_acc': 0, 'odometer': 58754.1349, 'engine_hours_type': '', 'odometer_type': ''}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-30T05:20:38.498+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-30T05:20:38.608+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-30T05:20:38.707+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-30T05:20:38.737+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-30T05:20:38.800+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.087s]
[2024-04-30T05:20:39.669+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-30T05:20:44.602+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:4.963s]
[2024-04-30T05:20:44.899+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 1 document(s) failed to index.
[2024-04-30T05:20:44.919+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=14, execution_date=20240430T050000, start_date=20240430T052014, end_date=20240430T052044
[2024-04-30T05:20:44.939+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24156 for task ETL_job (1 document(s) failed to index.; 655142)
[2024-04-30T05:20:45.002+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-30T05:20:45.031+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
