[2024-04-18T00:07:00.551+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-15T21:37:28.556433+00:00 map_index=2 [queued]>
[2024-04-18T00:07:00.633+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-15T21:37:28.556433+00:00 map_index=2 [queued]>
[2024-04-18T00:07:00.638+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 6
[2024-04-18T00:07:00.699+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-15 21:37:28.556433+00:00
[2024-04-18T00:07:00.717+0000] {standard_task_runner.py:60} INFO - Started process 366184 to run task
[2024-04-18T00:07:00.731+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'manual__2024-04-15T21:37:28.556433+00:00', '--job-id', '5756', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpc3t1utaw', '--map-index', '2']
[2024-04-18T00:07:00.740+0000] {standard_task_runner.py:88} INFO - Job 5756: Subtask ETL_job
[2024-04-18T00:07:00.885+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-15T21:37:28.556433+00:00 map_index=2 [running]> on host a09da322e808
[2024-04-18T00:07:01.162+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T21:37:28.556433+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T21:37:28.556433+00:00'
[2024-04-18T00:07:01.166+0000] {Units_dag.py:99} INFO - i: 20000, chunk: 10000
[2024-04-18T00:07:01.166+0000] {Units_dag.py:100} INFO - child token is::: None
[2024-04-18T00:07:01.167+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    units_list = Utils.get_all_units_api(args[0], args[1],child_token)
  File "/opt/airflow/dags/utilities.py", line 15, in get_all_units_api
    response = _ApiCaller.post(Globals.api_endpoint+"units/lists?token="+child_token, data_payload)
TypeError: can only concatenate str (not "NoneType") to str
[2024-04-18T00:07:01.195+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=2, execution_date=20240415T213728, start_date=20240418T000700, end_date=20240418T000701
[2024-04-18T00:07:01.236+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5756 for task ETL_job (can only concatenate str (not "NoneType") to str; 366184)
[2024-04-18T00:07:01.298+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-18T00:07:01.354+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
