[2024-04-18T00:10:33.133+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.split_data_into_chunks manual__2024-04-14T22:00:28.706459+00:00 [queued]>
[2024-04-18T00:10:33.221+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.split_data_into_chunks manual__2024-04-14T22:00:28.706459+00:00 [queued]>
[2024-04-18T00:10:33.222+0000] {taskinstance.py:2193} INFO - Starting attempt 9 of 11
[2024-04-18T00:10:33.607+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): split_data_into_chunks> on 2024-04-14 22:00:28.706459+00:00
[2024-04-18T00:10:33.626+0000] {standard_task_runner.py:60} INFO - Started process 367276 to run task
[2024-04-18T00:10:33.666+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'split_data_into_chunks', 'manual__2024-04-14T22:00:28.706459+00:00', '--job-id', '6280', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp3hao12j3']
[2024-04-18T00:10:33.719+0000] {standard_task_runner.py:88} INFO - Job 6280: Subtask split_data_into_chunks
[2024-04-18T00:10:34.172+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.split_data_into_chunks manual__2024-04-14T22:00:28.706459+00:00 [running]> on host a09da322e808
[2024-04-18T00:10:34.485+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='split_data_into_chunks' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T22:00:28.706459+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T22:00:28.706459+00:00'
[2024-04-18T00:10:34.527+0000] {Units_dag.py:78} INFO - type of length is :<class 'NoneType'>
[2024-04-18T00:10:34.527+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 84, in split_data_into_chunks
    if length > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
[2024-04-18T00:10:34.566+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=split_data_into_chunks, execution_date=20240414T220028, start_date=20240418T001033, end_date=20240418T001034
[2024-04-18T00:10:34.596+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6280 for task split_data_into_chunks ('>' not supported between instances of 'NoneType' and 'int'; 367276)
[2024-04-18T00:10:34.642+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-18T00:10:34.733+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
