[2024-05-10T05:44:37.744+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T05:20:00+00:00 map_index=10 [queued]>
[2024-05-10T05:44:37.790+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T05:20:00+00:00 map_index=10 [queued]>
[2024-05-10T05:44:37.790+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-05-10T05:44:37.862+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-10 05:20:00+00:00
[2024-05-10T05:44:37.880+0000] {standard_task_runner.py:60} INFO - Started process 906264 to run task
[2024-05-10T05:44:37.897+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-10T05:20:00+00:00', '--job-id', '46722', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpuqkvwbyi', '--map-index', '10']
[2024-05-10T05:44:37.906+0000] {standard_task_runner.py:88} INFO - Job 46722: Subtask ETL_job
[2024-05-10T05:44:38.133+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-10T05:20:00+00:00 map_index=10 [running]> on host a09da322e808
[2024-05-10T05:44:38.425+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T05:20:00+00:00'
[2024-05-10T05:44:38.429+0000] {Units_dag.py:98} INFO - i: 100000, chunk: 10000
[2024-05-10T05:44:38.430+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MzE5NjAzLCJleHAiOjE3MTc5MTE2MDMsIm5iZiI6MTcxNTMxOTYwMywianRpIjoidkF0TjVOOHQ2dm9MaXhZUiIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.xvA0Ycx_x7M2M_TdWILhUAO_A8qvPBJbnljNRSnzt6U
[2024-05-10T05:44:57.886+0000] {Units_dag.py:103} INFO - {'_id': '64579c5c21d2e935054c259d', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': 'H0200096 (7218-KAA)', 'operation_code': 'H0200096', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '350544507881558', 'sim_number': '+966830031794229', 'sim_serial': '421296730057', 'device_serial': '1125712112', 'device': 'teltonika', 'user_id': '62bb1bb23c00423a7b3af933', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-05-07 15:41:00', 'shipment_info': {'product_category': None, 'truck_type': None, 'shipment_type': None, 'shipment_payment_type': None, 'transporter_type': None, 'operating_area': None, 'weight_kilograms_per_day': None, 'kms_per_day': None, 'shipment_trip_drive_hrs_day': None, 'allowable_delay_drive_hrs_day': None, 'expected_shipment_trip_day': None, 'car_pay_per_day': None, 'exceeding_temperature_limit_per_day': None, 'temperature_upper_limit': None, 'exceeding_humidity_limit_per_day': None, 'humidity_upper_limit': None}, 'skip_sim_information': False, 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'al-yamama-trading-admin', 'last_update': {'dtt': 1714033935000, 'dts': 1714033940071, 'spd': 0, 'ang': 245, 'alt': 4, 'chPrams': {'Speed': {'v': 0, 'cdt': 1713343102000}, 'output1': {'v': False, 'cdt': 1713962063000}, 'output2': {'v': False, 'cdt': 1713962063000}, 'ePwrV': {'v': 0, 'cdt': 1714027302000}, 'parm24': {'v': 0, 'cdt': 1713343102000}, 'sat': {'v': 14, 'cdt': 1714033935000}, 'ai1': {'v': 87, 'cdt': 1713160755000}, 'priority': {'v': 0, 'cdt': 1711854936000}, 'di2': {'v': 0, 'cdt': 1712043865000}, 'type': {'v': 6, 'cdt': 1712470517000}, 'di1': {'v': 0, 'cdt': 1713756500000}, 'result': {'v': '5665723a30332e32372e31335f3033204750533a41584e5f352e312e392048773a464d42313230204d6f643a333320494d45493a33353035343435303738383135353820496e69743a323032342d332d323820373a343020557074696d653a32333438343238204d41433a333838413231313638344532205350433a312830292041584c3a32204f42443a3020424c3a312e31302042543a34', 'cdt': 1713961763000}, 'protocol': {'v': 'FMB120', 'cdt': 1713962063000}, 'parm6': {'v': 87, 'cdt': 1713951545000}, 'iPwrV': {'v': 3.378, 'cdt': 1714033935000}, 'event': {'v': 0, 'cdt': 1711854936000}}, 'prms': {'protocol': 'FMB120', 'priority': 0, 'sat': 14, 'event': 0, 'di1': 0, 'output1': 0, 'di2': 0, 'output2': 0, 'ePwrV': 0, 'Speed': 0, 'parm24': 0, 'iPwrV': 3.378, 'ai1': 87, 'parm6': 87}, 'devPrms': ['protocol', 'priority', 'sat', 'event', 'di1', 'output1', 'di2', 'output2', 'ePwrV', 'Speed', 'parm24', 'iPwrV', 'ai1', 'parm6'], 'old_params': {'Speed': 0, 'output1': 0, 'output2': 0, 'ePwrV': 0, 'parm24': 0, 'sat': 12, 'ai1': 87, 'priority': 0, 'di2': 0, 'di1': 0, 'protocol': 'teltonika', 'parm6': 87, 'iPwrV': 3.43, 'event': 0}, 'vLoc': 1, 'vCon': 1, 'ip': '51.39.51.171', 'rl': 0, 'trl': 6584.8175, 'mdu': 0, 'tmdu': 788987, 'eidl': 0, 'teidl': 10197356, 'fc': 0, 'tfc': 9.319368, 'acc': 0, 'accOn': 621567779, 'accOff': 19564701, 'sdu': 302, 'tsdu': 277435, 'lat': 27.9157, 'lng': 48.6868699}, 'counters': {'odometer_type': 'gps', 'odometer': 6654.6895, 'engine_hours_type': 'acc', 'engine_hours': 621567779, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-10T05:45:01.329+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T05:45:01.384+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T05:45:01.415+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-10T05:45:01.612+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T05:45:01.682+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.265s]
[2024-05-10T05:45:02.124+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T05:45:02.135+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.037s]
[2024-05-10T05:45:02.136+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-10T05:45:02.136+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-10T05:45:02.136+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-10T05:45:02.847+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.711s]
[2024-05-10T05:45:03.097+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 2771 document(s) failed to index.
[2024-05-10T05:45:03.112+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=10, execution_date=20240510T052000, start_date=20240510T054437, end_date=20240510T054503
[2024-05-10T05:45:03.128+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46722 for task ETL_job (2771 document(s) failed to index.; 906264)
[2024-05-10T05:45:03.166+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-10T05:45:03.188+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
