[2024-04-18T00:10:49.261+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:41:33.032415+00:00 map_index=13 [queued]>
[2024-04-18T00:10:49.337+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:41:33.032415+00:00 map_index=13 [queued]>
[2024-04-18T00:10:49.339+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-18T00:10:49.411+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-16 09:41:33.032415+00:00
[2024-04-18T00:10:49.456+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'manual__2024-04-16T09:41:33.032415+00:00', '--job-id', '6330', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp6n7w6e8t', '--map-index', '13']
[2024-04-18T00:10:49.437+0000] {standard_task_runner.py:60} INFO - Started process 367381 to run task
[2024-04-18T00:10:49.480+0000] {standard_task_runner.py:88} INFO - Job 6330: Subtask ETL_job
[2024-04-18T00:10:49.740+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:41:33.032415+00:00 map_index=13 [running]> on host a09da322e808
[2024-04-18T00:10:50.200+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T09:41:33.032415+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T09:41:33.032415+00:00'
[2024-04-18T00:10:50.209+0000] {Units_dag.py:99} INFO - i: 130000, chunk: 10000
[2024-04-18T00:10:50.210+0000] {Units_dag.py:100} INFO - child token is::: None
[2024-04-18T00:10:50.211+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    units_list = Utils.get_all_units_api(args[0], args[1],child_token)
  File "/opt/airflow/dags/utilities.py", line 15, in get_all_units_api
    response = _ApiCaller.post(Globals.api_endpoint+"units/lists?token="+child_token, data_payload)
TypeError: can only concatenate str (not "NoneType") to str
[2024-04-18T00:10:50.273+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=13, execution_date=20240416T094133, start_date=20240418T001049, end_date=20240418T001050
[2024-04-18T00:10:50.337+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6330 for task ETL_job (can only concatenate str (not "NoneType") to str; 367381)
[2024-04-18T00:10:50.426+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-18T00:10:50.507+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
