[2024-04-16T09:37:25.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:37:09.409595+00:00 map_index=10 [queued]>
[2024-04-16T09:37:25.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:37:09.409595+00:00 map_index=10 [queued]>
[2024-04-16T09:37:25.508+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-16T09:37:25.641+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-04-16 09:37:09.409595+00:00
[2024-04-16T09:37:25.683+0000] {standard_task_runner.py:60} INFO - Started process 329339 to run task
[2024-04-16T09:37:25.723+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'manual__2024-04-16T09:37:09.409595+00:00', '--job-id', '4018', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmp21w0vd7s', '--map-index', '10']
[2024-04-16T09:37:25.742+0000] {standard_task_runner.py:88} INFO - Job 4018: Subtask ETL_job
[2024-04-16T09:37:26.044+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job manual__2024-04-16T09:37:09.409595+00:00 map_index=10 [running]> on host a09da322e808
[2024-04-16T09:37:26.319+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T09:37:09.409595+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T09:37:09.409595+00:00'
[2024-04-16T09:37:26.320+0000] {Units_dag.py:90} INFO - i: 100000, chunk: 10000
[2024-04-16T09:37:26.321+0000] {Units_dag.py:91} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzEzMjYwMjMzLCJleHAiOjE3MTU4NTIyMzMsIm5iZiI6MTcxMzI2MDIzMywianRpIjoiRDZ3ZWJtMWlWQVRsaXg5byIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.SfjtHsGuT6rtlJJazNtFb6ijnPsov8inCQU_cBbuVvc
[2024-04-16T09:37:55.201+0000] {Units_dag.py:95} INFO - {'_id': '644f8030cb748e755e5fd0af', 'icon': 'icons/icon.png', 'driver_id': '64b90e16c7bce0690221f4a5', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '1687 T S A', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '868184060526095', 'sim_number': '+966830031798091', 'sim_serial': '421296732706', 'device_serial': '868184060526095', 'device': 'bce', 'user_id': '643c519a794d005c3c48dbf5', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2023-12-17 10:37:21', 'created_at': '2023-05-01 12:02:40', 'skip_sim_information': False, 'creator': 'amr.ahmed', 'company': '', 'owner': 'northern-border-university-admin', 'last_update': {'dtt': 1713259980000, 'dts': 1713260089504, 'spd': 0, 'ang': 180, 'alt': 548, 'chPrams': {'ePwrV': {'v': 12.186, 'cdt': 1713259980000}, 'di16': {'v': 1, 'cdt': 1712516080000}, 'rssi1': {'v': 72, 'cdt': 1713259980000}, 'di15': {'v': 0, 'cdt': 1713253970000}, 'di14': {'v': 0, 'cdt': 1713248988000}, 'di13': {'v': 0, 'cdt': 1713253970000}, 'di12': {'v': 0, 'cdt': 1713253970000}, 'di11': {'v': 0, 'cdt': 1713253970000}, 'di10': {'v': 0, 'cdt': 1713253970000}, 'di2': {'v': 1, 'cdt': 1713253970000}, 'di1': {'v': 0, 'cdt': 1713249018000}, 'di4': {'v': 0, 'cdt': 1713253970000}, 'di3': {'v': 0, 'cdt': 1713253970000}, 'di6': {'v': 1, 'cdt': 1713253970000}, 'di5': {'v': 0, 'cdt': 1713249088000}, 'lac1': {'v': 12107, 'cdt': 1711190738000}, 'protocol': {'v': 'bce', 'cdt': 1713253970000}, 'di8': {'v': 1, 'cdt': 1713253970000}, 'di7': {'v': 0, 'cdt': 1713249018000}, 'di9': {'v': 0, 'cdt': 1713253970000}, 'iPwrV': {'v': 3.967, 'cdt': 1713259680000}, 'cid1': {'v': 15191, 'cdt': 1712516094000}, 'odometer': {'v': 0, 'cdt': 1713257574000}, 'spd': {'v': 0, 'cdt': 1713248988000}, 'sat': {'v': 7, 'cdt': 1713259980000}, 'hdop': {'v': 2, 'cdt': 1713256074000}, 'ta': {'v': 0, 'cdt': 1713253970000}, 'mcc1': {'v': 420, 'cdt': 1713253970000}, 'mnc1': {'v': 4, 'cdt': 1713253970000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 7, 'hdop': 2, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 1, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 12.186, 'iPwrV': 3.967, 'ta': 0, 'mcc1': 420, 'mnc1': 4, 'lac1': 12107, 'cid1': 15191, 'rssi1': 72}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'di16': 1, 'ePwrV': 12.169, 'di15': 0, 'rssi1': 73, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di2': 1, 'di1': 0, 'di4': 0, 'di3': 0, 'di6': 1, 'di5': 0, 'lac1': 12107, 'protocol': 'bce', 'di8': 1, 'di7': 0, 'di9': 0, 'iPwrV': 3.967, 'cid1': 15191, 'odometer': 0, 'spd': 0, 'sat': 6, 'hdop': 2, 'ta': 0, 'mcc1': 420, 'mnc1': 4}, 'vLoc': 1, 'vCon': 1, 'ip': '51.39.7.152', 'rl': 0, 'trl': 12682.4428, 'mdu': 0, 'tmdu': 632412, 'eidl': 0, 'teidl': 410376, 'fc': 0, 'tfc': 0.017196, 'acc': 0, 'accOn': 3823174, 'accOff': 25515428, 'sdu': 300, 'tsdu': 10892, 'lat': 30.916160583496094, 'lng': 41.076904296875}, 'counters': {'odometer_type': 'gps', 'odometer': 12681.3077, 'engine_hours_type': 'acc', 'engine_hours': 3823174, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-04-16T09:37:55.767+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:37:55.809+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:37:55.853+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-04-16T09:37:55.857+0000] {_transport.py:358} INFO - GET https://dbelk3.afaqy.local:9200/_cluster/health [status:N/A duration:0.002s]
[2024-04-16T09:37:55.858+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-04-16T09:37:55.859+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7faa184684f0>: Failed to establish a new connection: [Errno 111] Connection refused)
[2024-04-16T09:37:55.879+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T09:37:55.952+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.091s]
[2024-04-16T09:37:56.661+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-04-16T09:37:56.891+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.259s]
[2024-04-16T09:37:56.970+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 103, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-04-16T09:37:56.982+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=10, execution_date=20240416T093709, start_date=20240416T093725, end_date=20240416T093756
[2024-04-16T09:37:57.001+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4018 for task ETL_job (10000 document(s) failed to index.; 329339)
[2024-04-16T09:37:57.075+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-16T09:37:57.104+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
