[2024-05-07T00:20:16.069+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T00:00:00+00:00 map_index=0 [queued]>
[2024-05-07T00:20:16.152+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T00:00:00+00:00 map_index=0 [queued]>
[2024-05-07T00:20:16.152+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-07T00:20:16.261+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-07 00:00:00+00:00
[2024-05-07T00:20:16.288+0000] {standard_task_runner.py:60} INFO - Started process 820467 to run task
[2024-05-07T00:20:16.347+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-07T00:00:00+00:00', '--job-id', '36896', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpgw0501bh', '--map-index', '0']
[2024-05-07T00:20:16.349+0000] {standard_task_runner.py:88} INFO - Job 36896: Subtask ETL_job
[2024-05-07T00:20:16.698+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T00:00:00+00:00 map_index=0 [running]> on host a09da322e808
[2024-05-07T00:20:17.125+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-07T00:00:00+00:00'
[2024-05-07T00:20:17.131+0000] {Units_dag.py:99} INFO - i: 0, chunk: 10000
[2024-05-07T00:20:17.131+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MDQxMjAzLCJleHAiOjE3MTc2MzMyMDMsIm5iZiI6MTcxNTA0MTIwMywianRpIjoidG5uVExqR21zbDRuMWtlTyIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.Wb92_MoLdnWqC-Bd3mas6bJRu8jWfsFW6k6XaQtjLgg
[2024-05-07T00:20:49.089+0000] {Units_dag.py:104} INFO - {'_id': '5c3b1d7303ed52664c40f2c5', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': 'ddffffff', 'plate_number': '8222222f', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'name': 'yasser nabeh', 'imei': '867459040839029', 'sim_number': '', 'sim_serial': '', 'device_serial': '867459040839029', 'device': 'bceIotm', 'created_by': '5b5475eeec689d30c527f124', 'user_id': '5b5475eeec689d30c527f124', 'operation_code': '51420085', 'updated_at': '2024-05-01 07:52:12', 'device_type': 'fixed_unit', 'business_types': {'waste': False, 'transportation': False, 'water': False, 'hajj': False}, 'device_gateway': '', 'gateway': False, 'deleted_at': '', 'skip_sim_information': True, 'cctv': {'dvr_id': '', 'channels': 1}, 'shipment_info': {'product_category': 'frozen_meat', 'truck_type': 'bulker_40_footer', 'shipment_type': 'long_haul', 'shipment_payment_type': 'trip_paid', 'transporter_type': 't typw', 'operating_area': 'oparea', 'weight_kilograms_per_day': 1, 'kms_per_day': 2, 'shipment_trip_drive_hrs_day': 1, 'allowable_delay_drive_hrs_day': 1, 'expected_shipment_trip_day': 1, 'car_pay_per_day': 1, 'exceeding_temperature_limit_per_day': 1, 'temperature_upper_limit': 1, 'exceeding_humidity_limit_per_day': 1, 'humidity_upper_limit': 1}, 'custom_fields': [{'id': '6621020a721cc3fb8c0b7ca4', 'key': 'test-1', 'value': 'value-1', 'type': 'general', 'measurement_unit': ''}, {'id': '6621020a721cc3fb8c0b7ca6', 'key': 'test-4', 'value': 'value-4', 'type': 'general', 'measurement_unit': ''}, {'id': '6621020a721cc3fb8c0b7ca8', 'key': 'test-3', 'value': 'value-3', 'type': 'general', 'measurement_unit': ''}, {'id': '6621020a721cc3fb8c0b7caa', 'key': 'test-2', 'value': 'value-2', 'type': 'general', 'measurement_unit': ''}], 'creator': 'afaqy', 'company': '', 'owner': 'afaqy', 'last_update': {'dtt': 1714461864792, 'dts': 1714461962788, 'spd': 60, 'ang': 0, 'alt': 28, 'chPrams': {'sat': {'v': '12', 'cdt': 1714461862914}, 'temp2': {'v': '15', 'cdt': 1714399279052}, 'Temp6': {'v': '-50', 'cdt': 1714461862914}, 'temp3': {'v': '-6', 'cdt': 1714399279052}, 'Temp5': {'v': '-13', 'cdt': 1714461862914}, 'Temp4': {'v': '-0.9', 'cdt': 1714461862914}, 'Temp3': {'v': '30', 'cdt': 1714461862914}, 'temp6': {'v': '120', 'cdt': 1714399279052}, 'di5': {'v': '0', 'cdt': 1714461862914}, 'Temp2': {'v': '10', 'cdt': 1714399845265}, 'Temp1': {'v': '0', 'cdt': 1714461862914}, 'temp4': {'v': '20', 'cdt': 1714399279052}, 'temp5': {'v': '100', 'cdt': 1714399279052}}, 'prms': {'di5': '0', 'sat': '12', 'Temp1': '0', 'Temp2': '10', 'Temp3': '30', 'Temp4': '-0.9', 'Temp5': '-13', 'Temp6': '-50'}, 'devPrms': ['di5', 'sat', 'Temp1', 'Temp2', 'Temp3', 'Temp4', 'Temp5', 'Temp6'], 'old_params': {'di5': '0', 'sat': '12', 'Temp1': '0', 'Temp2': '10', 'Temp3': '30', 'Temp4': '-0.9', 'Temp5': '-13', 'Temp6': '-50'}, 'vLoc': 1, 'vCon': 1, 'ip': '156.215.28.59', 'rl': 0, 'trl': 0, 'mdu': 0, 'tmdu': 0, 'eidl': 0, 'teidl': 0, 'fc': 0, 'tfc': 0, 'acc': 0, 'accOn': 0, 'accOff': 0, 'sdu': 0, 'tsdu': 0, 'lat': 25.489138151307813, 'lng': 46.88460248065079}, 'counters': {'odometer_type': 'gps', 'odometer': 0, 'engine_hours_type': 'acc', 'engine_hours': 0, 'last_acc': None}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-07T00:20:50.241+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T00:20:50.329+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T00:20:50.446+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T00:20:50.478+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T00:20:50.536+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.088s]
[2024-05-07T00:20:51.625+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T00:20:51.658+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.060s]
[2024-05-07T00:20:51.659+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-07T00:20:51.659+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-07T00:20:51.660+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T00:20:58.227+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-05-07T00:20:58.231+0000] {process_utils.py:131} INFO - Sending 15 to group 820467. PIDs of all processes in the group: [820467]
[2024-05-07T00:20:58.231+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 820467
[2024-05-07T00:20:58.232+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-07T00:20:58.234+0000] {_transport.py:358} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:N/A duration:6.575s]
[2024-05-07T00:20:58.235+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk1.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-07T00:20:58.236+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: AirflowException(Task received SIGTERM signal)
[2024-05-07T00:20:58.243+0000] {_node_pool.py:312} INFO - Resurrected node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> (force=False)
[2024-05-07T00:20:58.245+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T00:20:58.261+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.017s]
[2024-05-07T00:20:58.262+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 2 times in a row, putting on 2 second timeout
[2024-05-07T00:20:58.263+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 2 of 3)
[2024-05-07T00:20:59.063+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T00:21:01.539+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:3.277s]
[2024-05-07T00:21:01.871+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-07T00:21:01.889+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=0, execution_date=20240507T000000, start_date=20240507T002016, end_date=20240507T002101
[2024-05-07T00:21:01.982+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=820467, status='terminated', exitcode=0, started='00:20:15') (820467) terminated with exit code 0
